# Generated by Django 3.0.1 on 2020-01-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='prescription',
            new_name='prescriptions',
        ),
    ]
