# Generated by Django 3.0.1 on 2020-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_auto_20200124_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='prescriptions',
            field=models.TextField(max_length=1000),
        ),
    ]
